# Configuration for Universal and Single Panel primer Snakemake pipeline.


# 1) This is where the original bam files can be found. (glob)
raw_path: /path/to/runs/BAMs_for_analysis/*/*bam

# 2) This is where the **REMAPPED** bam files can be found. (glob)
tmap_path: tmap/A*/*bam

# 3) This is name of the deliverable directory.
deliver_proj: Type_Study_RD###_YearMonthDay

# 4) Select mapq threshold.
aq_filter: 4

# 5) Choose minimum read depth for fasta files.
min_read: 4

# 6) Choose cutoff for % Ns in the final fasta.
fasta_n: 75


hpv_reference: /path/to/references/HPV/TMAP_Refs/HPVRef_Alphas65_Pad400_hg19/HPV_Ref_Alphas65_Pad400_hg19.fasta
amplicon_bed: /path/to/references/HPV/universal_bed/old_HPVRef_13Types_Ref_Mapped_hg19.unmerged-detail_20160414.bed
len_bed: /path/to/references/HPV/len_bed/hpv_universal.bed


# Tools and packages

vc_bin: /path/to/references/HPV/tvc-5.0.3/bin
vc_pipe: /path/to/references/HPV/tvc-5.0.3/bin/variant_caller_pipeline.py
vc_param: /path/to/references/HPV/germline_low_stringency_no_het_low_depth.json
cov_dev: /path/to/references/HPV/cgrCoverageDev
glu: /path/to/references/HPV/glu

# SNPEFF
# any new HPV types need to be added to the hpv_universal database and the annotations txt below
snpeff: /path/to/references/snpEff
snpeff_bed: /path/to/references/HPV/universal_annotations_20170106.txt # includes all types
genes_gtf: /path/to/references/snpEff/data/hpv_universal/genes.gtf # includes all types
